### ISSUE TITLE
[Feature] Rounded Corners

### ISSUE THREAD

**Issue by fr00kt** [zuzumi-f/Discord-11#10]
Is it possible to make rounded corners of the main window like in windows 11?

**Comment by zuzumi-f** [comment]
yep, you can use this
```css
.appMount-2yBXZl, body {
    border-radius: 8px;
    background-color: transparent;
}
```
