### ISSUE TITLE
[Feature] Horizontal Server List Support

### ISSUE THREAD

**Issue by Shadow514** [zuzumi-f/Discord-11#4]
Could you make the theme support the Horizontal Server List?
because when ever I enable HSL the settings modal and other modals just looks weird.
![4935f779f92168c455b12bee26655b71](https://user-images.githubusercontent.com/93408587/158002274-961ef904-1597-4363-87e5-f2bf2ba3d9dd.png)

**Comment by zuzumi-f** [comment]
the themes are not compatible, sorry

**Comment by zuzumi-f** [comment]
Sorry for be late
I made a code for HSL
You can use this

```css

#app-mount .standardSidebarView-E9Pc3j {
    border-radius: 0;
    border-left: none;
    width: 100%;
    left: 0;
    height: calc(100% - 60px);
    top: unset;
    bottom: 0;
}
```
